import {
	AiFillGithub,
	SiBootstrap,
	SiCplusplus,
	SiCss3,
	SiDart,
	SiExpress,
	SiFlutter,
	SiGit,
	SiGraphql,
	SiHtml5,
	SiJava,
	SiJavascript,
	SiMysql,
	SiNetlify,
	SiPython,
	SiReact,
	SiRedux,
	SiTailwindcss,
	SiVisualstudiocode,
	SiCsharp,
	SiSpringboot,
	SiPostgresql,
	SiPostman,
	SiRedis,
	SiDotnet,
	SiDocker,
	SiVite,
} from "react-icons/all";

export const SKILLS_LIST = [
	{
		title: "Programming Languages",
		items: [
			{ id: "pl-1", icon: SiPython, name: "Python" },
			{ id: "pl-2", icon: SiCsharp, name: "C#" },
			{ id: "pl-3", icon: SiJava, name: "Java" },
			{ id: "pl-4", icon: SiCplusplus, name: "C++" },
			{ id: "pl-5", icon: SiHtml5, name: "HTML" },
			{ id: "pl-6", icon: SiCss3, name: "CSS" },
			{ id: "pl-7", icon: SiJavascript, name: "JavaScript" },
			{ id: "pl-8", icon: SiDart, name: "Dart" },
		],
	},
	{
		title: "Frameworks/Libraries",
		items: [
			{ id: "f-2", icon: SiDotnet, name: ".NET" },
			{ id: "f-3", icon: SiSpringboot, name: "Spring Boot" },
			{ id: "f-5", icon: SiBootstrap, name: "Bootstrap" },
			{ id: "f-6", icon: SiTailwindcss, name: "Tailwind CSS" },
			{ id: "f-7", icon: SiExpress, name: "Express" },
			{ id: "f-1", icon: SiReact, name: "ReactJS" },
			{ id: "f-8", icon: SiRedux, name: "Redux" },
			{ id: "f-9", icon: SiFlutter, name: "Flutter" },
		],
	},
	{
		title: "Tools",
		items: [
			{ id: "t-1", icon: SiMysql, name: "MySQL" },
			{ id: "t-2", icon: SiPostgresql, name: "PostgreSQL" },
			{ id: "t-3", icon: SiDocker, name: "Docker" },
			{ id: "t-4", icon: SiGit, name: "Git" },
			{ id: "t-5", icon: SiRedis, name: "Redis" },
			{ id: "t-6", icon: AiFillGithub, name: "GitHub" },
			{ id: "t-7", icon: SiNetlify, name: "Netlify" },
			{ id: "t-8", icon: SiVite, name: "ViteJS" },
			{ id: "t-9", icon: SiVisualstudiocode, name: "VS Code" },
			{ id: "t-10", icon: SiPostman, name: "Postman" },
		],
	},
];
